INSERT INTO messages (message_id,
                      phone_number,
                      message_content,
                      sending_status,
                      created_at,
                      updated_at)
VALUES (gen_random_uuid(),
        '+905558889900',
        'example message content - 1',
        'sent',
        NOW(),
        NOW()),
       (gen_random_uuid(),
        '+905558889911',
        'example message content - 2',
        'waiting',
        NOW(),
        NOW()),
       (gen_random_uuid(),
        '+905558889922',
        'example message content - 3',
        'failed',
        NOW(),
        NOW()),
       (gen_random_uuid(),
        '+905558889911',
        'example message content - 4',
        'waiting',
        NOW(),
        NOW()),
       (gen_random_uuid(),
        '+905558889911',
        'example message content - 5',
        'waiting',
        NOW(),
        NOW()),
       (gen_random_uuid(),
        '+905558889911',
        'example message content - 6',
        'waiting',
        NOW(),
        NOW()),
       (gen_random_uuid(),
        '+905558889912',
        'example message content - 7',
        'waiting',
        NOW(),
        NOW()),
       (gen_random_uuid(),
        '+905558889913',
        'example message content - 8',
        'waiting',
        NOW(),
        NOW()),
       (gen_random_uuid(),
        '+905558889914',
        'example message content - 9',
        'waiting',
        NOW(),
        NOW()),
       (gen_random_uuid(),
        '+905558889915',
        'example message content - 10',
        'waiting',
        NOW(),
        NOW());
